plugins {
    id("org.springframework.boot")
    id("io.spring.dependency-management")
}

dependencies {
    implementation(project(":backend:modules:identity"))
    implementation(project(":backend:modules:channel"))
    implementation(project(":backend:modules:expression"))
    implementation(project(":backend:modules:experience"))
    implementation(project(":backend:modules:gateway"))
    implementation(project(":backend:modules:guild"))
    implementation(project(":backend:modules:invite"))
    implementation(project(":backend:modules:message"))
    implementation(project(":backend:modules:moderation"))
    implementation(project(":backend:modules:permission"))
    implementation(project(":backend:modules:presence"))
    implementation(project(":backend:modules:social"))
    implementation(project(":backend:modules:storage"))
    implementation(project(":backend:modules:thread"))
    implementation(project(":backend:modules:user"))
    implementation(project(":backend:modules:voice"))
    implementation(project(":backend:shared:common"))
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-websocket")
    implementation("org.springframework.security:spring-security-crypto:6.4.2")
    implementation("org.flywaydb:flyway-core")
    implementation("org.flywaydb:flyway-database-postgresql")
    implementation("org.postgresql:postgresql")
    runtimeOnly("commons-logging:commons-logging:1.3.4")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("com.tngtech.archunit:archunit-junit5:1.3.0")
}
