package com.example.discord.moderation;

public enum AuditLogAction {
    ONBOARDING_ANSWER_SUBMITTED,
    AUTOMOD_RULE_CREATED,
    AUTOMOD_MESSAGE_BLOCKED,
    PREMIUM_ENTITLEMENT_GRANTED,
    PREMIUM_ENTITLEMENT_CANCELED,
    PREMIUM_ENTITLEMENT_EXPIRED
}
