package com.example.discord.moderation;

public enum AuditLogAction {
    ONBOARDING_ANSWER_SUBMITTED,
    AUTOMOD_RULE_CREATED,
    AUTOMOD_MESSAGE_BLOCKED,
    PREMIUM_ENTITLEMENT_GRANTED,
    PREMIUM_ENTITLEMENT_CANCELED,
    PREMIUM_ENTITLEMENT_EXPIRED,
    ROLE_ASSIGNED,
    INVITE_DELETED,
    MESSAGE_DELETED,
    MESSAGE_PINNED,
    MESSAGE_UNPINNED,
    STAGE_SPEAKER_APPROVED,
    STAGE_AUDIENCE_MOVED
}
