spring:
  config:
    import: optional:configtree:${DISCORD_JWT_CONFIG_TREE:/etc/discord-config/}
  application:
    name: websocket-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: health
