spring:
  config:
    import: optional:configtree:${DISCORD_JWT_CONFIG_TREE:/etc/discord-config/}
  application:
    name: websocket-service
management:
  endpoints:
    web:
      exposure:
        include: health
