$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$routingDir = Join-Path $repoRoot 'qa/c4-chat-scale'
$policyPath = Join-Path $routingDir 'routing-policy.ps1'
$testsPath = Join-Path $routingDir 'routing-policy.tests.ps1'
$composePath = Join-Path $routingDir 'docker-compose.yml'
$replicaEntrypointPath = Join-Path $routingDir 'replica-entrypoint.sh'
$replicationInitPath = Join-Path $routingDir 'init/000-replication.sh'
$schemaPath = Join-Path $routingDir 'init/001-schema.sql'
$pgbenchDir = Join-Path $routingDir 'pgbench'
$writePath = Join-Path $pgbenchDir 'write.sql'
$historyPath = Join-Path $pgbenchDir 'history.sql'
$searchPath = Join-Path $pgbenchDir 'search.sql'
$runPath = Join-Path $routingDir 'run.ps1'
$verifyPath = Join-Path $routingDir 'verify.ps1'
$readmePath = Join-Path $routingDir 'README.md'
$allowedTables = @('messages_baseline', 'messages_date_range', 'messages_date_hash')

function Assert($condition, $message) {
    if (-not $condition) {
        throw $message
    }
}

Assert (Test-Path $policyPath) 'routing-policy.ps1 is missing'
Assert (Test-Path $testsPath) 'routing-policy.tests.ps1 is missing'
Assert (Test-Path $composePath) 'docker-compose.yml is missing'
Assert (Test-Path $schemaPath) 'init/001-schema.sql is missing'
Assert (Test-Path $replicaEntrypointPath) 'replica-entrypoint.sh is missing'
Assert (Test-Path $replicationInitPath) 'init/000-replication.sh is missing'
Assert (Test-Path $runPath) 'run.ps1 is missing'
Assert (Test-Path $verifyPath) 'verify.ps1 is missing'
Assert (Test-Path $readmePath) 'README.md is missing'
foreach ($path in @($writePath, $historyPath, $searchPath)) {
    Assert (Test-Path $path) "pgbench script is missing: $path"
}

foreach ($path in @($policyPath, $testsPath, $runPath, $PSCommandPath)) {
    $tokens = $null
    $errors = $null
    [System.Management.Automation.Language.Parser]::ParseFile($path, [ref] $tokens, [ref] $errors) | Out-Null
    Assert ($errors.Count -eq 0) "PowerShell parse failed: $path"
}

$policy = Get-Content -Path $policyPath -Raw
$tests = Get-Content -Path $testsPath -Raw
$compose = Get-Content -Path $composePath -Raw
$replicaEntrypoint = Get-Content -Path $replicaEntrypointPath -Raw
$replicationInit = Get-Content -Path $replicationInitPath -Raw
$schema = Get-Content -Path $schemaPath -Raw
$write = Get-Content -Path $writePath -Raw
$history = Get-Content -Path $historyPath -Raw
$search = Get-Content -Path $searchPath -Raw
$run = Get-Content -Path $runPath -Raw
$verify = Get-Content -Path $verifyPath -Raw
$readme = Get-Content -Path $readmePath -Raw

Assert ($policy -match '(?m)^function\s+Get-ShardId\b') 'Get-ShardId function is missing'
Assert ($policy.Contains('[ArgumentException]')) 'ArgumentException validation is missing'
Assert ($policy.Contains('SHA256')) 'SHA-256 hashing is missing'
Assert ($policy.Contains('ToUInt32')) 'little-endian hash extraction is missing'
Assert ($tests.Contains('C4_ROUTING_TEST_PASS')) 'routing test pass marker is missing'
Assert ($tests.Contains('RED') -or $tests.Contains('routing-policy.ps1')) 'RED test contract is missing'

foreach ($snippet in @('primary:', 'replica:', 'pgbench:', 'postgres:16-alpine', '15442:5432', '15443:5432', 'wal_level=replica', 'replica-entrypoint.sh', 'pg_wal_replay_pause', 'profiles:', 'load', 'entrypoint: [pgbench]', '-Dtable=messages_baseline', 'c4-chat-scale-replica-data:/var/lib/postgresql/data')) {
    Assert ($compose.Contains($snippet)) "compose required snippet is missing: $snippet"
}
foreach ($snippet in @('shared_buffers=32MB', 'max_connections=32', 'work_mem=1MB')) {
    Assert ($compose.Contains($snippet)) "compose controlled benchmark setting is missing: $snippet"
}
Assert ($compose -match '(?ms)replica:.*entrypoint:\s*\[/bin/sh,\s*/usr/local/bin/replica-entrypoint\.sh\]') 'replica must use the bootstrap entrypoint'
Assert (-not $compose.Contains('REPLICA_BASEBACKUP_COMMAND')) 'replica bootstrap must not be an environment-only command'
Assert (-not $compose.Contains('primary_conninfo=')) 'replica primary_conninfo must be generated by pg_basebackup -R'
foreach ($table in $allowedTables) {
    Assert ($compose.Contains($table)) "compose must document the table allowlist entry: $table"
}
foreach ($snippet in @('pg_basebackup', '-h primary', '-D "$PGDATA"', '-U replication', '-R', '-S c4_chat_scale_slot', '-X stream', '-C', 'standby.signal', 'primary_conninfo')) {
    Assert ($replicaEntrypoint.Contains($snippet)) "replica entrypoint required snippet is missing: $snippet"
}
Assert ($replicaEntrypoint -match '(?ms)pg_basebackup.*-R\s+-S\s+c4_chat_scale_slot') 'pg_basebackup must create standby.signal and primary_conninfo from the replication slot'
foreach ($snippet in @('host replication replication', 'scram-sha-256')) {
    Assert ($replicationInit.Contains($snippet)) "replication pg_hba snippet is missing: $snippet"
}
foreach ($identifier in @('messages_template', 'messages_baseline', 'messages_date_range', 'messages_date_hash', 'PARTITION BY RANGE', 'PARTITION BY HASH', 'UNIQUE (chat_room_id, sequence, event_date)', 'idempotency_key', 'event_date', 'chat_room_id', '0..29', '0..15', 'MODULUS 16')) {
    Assert ($schema.Contains($identifier)) "schema required identifier is missing: $identifier"
}
Assert ($schema -match '(?i)messages_template_idempotency_unique\s+UNIQUE\s*\(\s*idempotency_key\s*,\s*event_date\s*,\s*chat_room_id\s*\)') 'template idempotency uniqueness is missing'
Assert ($schema -match '(?i)messages_date_range_idempotency_unique\s+UNIQUE\s*\(\s*idempotency_key\s*,\s*event_date\s*,\s*chat_room_id\s*\)') 'date_range idempotency uniqueness is missing'
Assert ($schema -match '(?i)messages_date_hash_idempotency_unique\s+UNIQUE\s*\(\s*idempotency_key\s*,\s*event_date\s*,\s*chat_room_id\s*\)') 'date_hash idempotency uniqueness is missing'
Assert ($schema.Contains('duplicate keys are rejected by the constraint')) 'idempotency duplicate behavior must be documented'
Assert ($write -match '(?i)INSERT\s+INTO\s+:table') 'write SQL must use allowlisted :table variable'
Assert ($write -match '(?i)ON\s+CONFLICT\s*\(\s*chat_room_id\s*,\s*sequence\s*,\s*event_date\s*\)\s*DO\s+NOTHING') 'write SQL must use partition-safe idempotent conflict target'
foreach ($sql in @($write, $history, $search)) {
    Assert ($sql.Contains(':table')) 'all pgbench SQL must exercise the run-selected table'
    Assert ($sql.Contains('allowlist')) 'pgbench table variable must be documented as allowlist-only'
    $sqlWithoutComments = [regex]::Replace($sql, '(?m)--.*$', '')
    foreach ($table in $allowedTables) {
        Assert (-not ($sqlWithoutComments -match "(?i)\b$table\b")) "pgbench SQL must not hard-code table: $table"
    }
}
Assert ($write.Contains('run.ps1') -or $compose.Contains('run.ps1')) 'table variable must document run.ps1 allowlist ownership'
Assert ($history -match '(?i)sequence\s*>\s*:cursor') 'history SQL must use ordered sequence cursor'
Assert ($history -match '(?i)chat_room_id') 'history SQL must constrain chat room'
Assert ($search -match '(?i)chat_room_id') 'search SQL must constrain chat room'
Assert ($search -match '(?i)event_date') 'search SQL must constrain event date'

Assert ($run -match '(?m)\[ValidateSet\(\x27baseline\x27,\x27date_range\x27,\x27date_hash\x27,\x27all\x27\)\]') 'run Variant ValidateSet is missing'
Assert ($run -match '(?m)\[ValidateRange\(1,') 'run DurationMinutes validation is missing'
Assert ($run -match '(?m)\$DurationMinutes\s*=\s*40') 'run default duration must be 40 minutes'
Assert ($run -match '(?m)\$Seed\s*=\s*1714') 'run default seed must be 1714'
foreach ($table in $allowedTables) { Assert ($run.Contains($table)) "run table allowlist is missing: $table" }
Assert ($run.Contains('up -d primary replica')) 'run must start primary and replica'
Assert ($run.Contains('--no-deps') -and $run.Contains(' -l -j 4 ')) 'run pgbench must log transactions and avoid dependency recreation'
Assert ($run.Contains('PGPASSWORD=dev_only_password')) 'run pgbench connection password must be explicit runtime-only value'
Assert ($run.Contains('pg_isready') -and $run.Contains('120')) 'run must poll pg_isready with 120 second timeout'
Assert ($run.Contains('down -v --remove-orphans')) 'run cleanup is missing'
foreach ($artifact in @('run.json', 'latency.tsv', 'db-stats.tsv', 'replica-lag.tsv', 'cursor-gaps.tsv', 'plans')) {
    Assert ($run.Contains($artifact)) "run artifact is missing: $artifact"
}
Assert ($run.Contains('variant`tphase`toperation`tcount`terror_count`terror_rate`tp50_ms`tp95_ms`tp99_ms`tmax_ms') -or
    $run.Contains('variant\tphase\toperation\tcount\terror_count\terror_rate\tp50_ms\tp95_ms\tp99_ms\tmax_ms')) 'latency.tsv percentile header is missing'
foreach ($snippet in @('decision.json','pruning evidence missing','artifact path must be under qa/artifacts/c4-chat-scale','C4_CHAT_SCALE_VERIFY_PASS')) {
    Assert ($verify.Contains($snippet)) "verify requirement is missing: $snippet"
}
foreach ($snippet in @('cursor-gaps.tsv','40-minute run required','all three variants are required','sensitive fields')) {
    Assert ($verify.Contains($snippet)) "verify fail-closed requirement is missing: $snippet"
}
foreach ($snippet in @('function Get-LatencySamples', 'function Get-Percentile', 'number of transactions actually processed', 'number of failed transactions', 'Ceiling', 'p50_ms', 'p95_ms', 'p99_ms', 'max_ms')) {
    Assert ($run.Contains($snippet)) "latency percentile helper requirement is missing: $snippet"
}
Assert ($run -match '(?i)latency.*sample|sample.*latency') 'run must fail closed when latency samples are unavailable'
Assert ($run -match '(?i)secret|password|dsn') 'run must explicitly guard secret output'
Assert (-not ($run -match '(?i)raw body|password.*run\.json|secret.*run\.json')) 'run must not write secrets or raw bodies'
foreach ($snippet in @('-v $artifactDir:/artifacts', '--log-prefix=/artifacts/pgbench-${variant}-${phase}-${op}', 'Add-Stats', 'Start-Job', 'Stop-Job', 'pg_stat_user_tables', 'pg_stat_replication', 'Start-Sleep -Seconds 10')) {
    Assert ($run.Contains($snippet)) "run interval evidence requirement is missing: $snippet"
}
Assert ($run.Contains('aggregateInterval = 10')) 'pgbench aggregate interval must be 10 seconds'
foreach ($snippet in @(
    'pwsh -NoProfile -File qa/c4-chat-scale.contract.ps1',
    'pwsh -NoProfile -File qa/c4-chat-scale/run.ps1 -Variant all -DurationMinutes 40',
    'pwsh -NoProfile -File qa/c4-chat-scale/verify.ps1 -ArtifactDir qa/artifacts/c4-chat-scale/<run-id>'
)) {
    Assert ($readme.Contains($snippet)) "README required command is missing: $snippet"
}

$testOutput = & pwsh -NoProfile -File $testsPath 2>&1
Assert ($LASTEXITCODE -eq 0) "Routing behavior test failed: $($testOutput -join [Environment]::NewLine)"
Assert (($testOutput -join [Environment]::NewLine).Contains('C4_ROUTING_TEST_PASS')) 'Routing behavior test did not report pass marker'

$composeConfig = & docker compose -f $composePath config 2>&1
Assert ($LASTEXITCODE -eq 0) "docker compose config failed: $($composeConfig -join [Environment]::NewLine)"

Write-Output 'C4_CHAT_SCALE_CONTRACT_PASS'
