param(
  [Parameter(Mandatory = $true)]
  [string] $Id,
  [Parameter(Mandatory = $true)]
  [string] $Title,
  [string] $Type = 'qa-infra',
  [string] $Priority = 'P1',
  [switch] $Force
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$date = Get-Date -Format 'yyyy-MM-dd'

function ConvertTo-Slug($value) {
  $slug = $value.ToLowerInvariant() -replace '[^a-z0-9]+', '-'
  return $slug.Trim('-')
}

function Write-NewFile($relativePath, $content) {
  $path = Join-Path $repoRoot $relativePath
  if ((Test-Path $path) -and -not $Force) {
    throw "Refusing to overwrite existing file without -Force: $relativePath"
  }
  $parent = Split-Path -Parent $path
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  Set-Content -Path $path -Value $content -Encoding UTF8
}

$slug = ConvertTo-Slug $Title
$baseName = "$Id-$slug"

$planPath = "docs/01-plan/features/$baseName.plan.md"
$designPath = "docs/02-design/features/$baseName.design.md"
$analysisPath = "docs/03-analysis/$baseName.analysis.md"
$reportPath = "docs/04-report/$baseName.report.md"
$feedbackPath = "docs/05-feedback/$baseName.feedback.md"
$backlogPath = Join-Path $repoRoot 'docs/03-tasking/improvement-task-backlog.md'

$plan = @"
# $Id $Title Plan

Created: $date
PDCA Phase: Plan
Slice: $Id $Title
Type: $Type
Priority: $Priority

## Executive Summary

| View | Content |
| --- | --- |
| Problem | Define the concrete problem this ticket solves. |
| Solution | Implement the smallest verifiable change for this ticket. |
| Function UX Effect | Future agents can understand scope, run the right tools, and record evidence consistently. |
| Core Value | Repeatable PDCA execution with explicit verification and feedback records. |

## Scope

- Define the repository paths this ticket may change.
- Define the behavior or documentation this ticket delivers.
- Define required verification evidence.

## Out of Scope

- Unrelated refactors.
- Production deployment changes unless explicitly listed.
- Unsafe or unbounded command execution.

## Success Criteria

- Plan, Design, Analysis, Report, and Feedback documents exist.
- Allowed Write Paths are explicit before implementation starts.
- Verification Commands are listed and later recorded with results.

## Failure Criteria

- Work proceeds without bounded write paths.
- Verification evidence is not recorded.
- Failures are not captured in the feedback document.
"@

$design = @"
# $Id $Title Design

Created: $date
PDCA Phase: Design
Slice: $Id $Title

## Architecture Decision

Describe the selected design and why it fits the current repository patterns.

## Allowed Write Paths

- `docs/**`

## Forbidden Changes

- Do not modify unrelated product behavior.
- Do not introduce arbitrary command execution.
- Do not commit runtime artifacts or secrets.

## Agent Packet

~~~text
Task ID: $Id
Goal: $Title
Required docs:
- $planPath
- $designPath
Allowed write paths:
- docs/**
Read-only context paths:
- docs/03-tasking/agent-team-operating-model.md
- qa/harness/README.md
Forbidden changes:
- No unrelated refactors
Expected tests:
- pwsh qa/agent-harness.ps1 -Tool ci-workflow-contract
Expected artifacts:
- docs/03-analysis/$baseName.analysis.md
- docs/04-report/$baseName.report.md
Return format:
- status
- changed files
- tests run and result
- residual risks
~~~

## Verification Commands

~~~powershell
pwsh qa/agent-harness.ps1 -Tool ci-workflow-contract
~~~

## Risks

- The ticket may need narrower write paths before implementation.
- Runtime verification may require local services depending on scope.
"@

$analysis = @"
# $Id $Title Analysis

Created: $date
PDCA Phase: Check
Slice: $Id $Title

## Verification Evidence

| Command | Result | Evidence |
| --- | --- | --- |
| TBD | TBD | TBD |

## Success Criteria Review

| Criteria | Status | Evidence |
| --- | --- | --- |
| Plan/Design exists | TBD | $planPath, $designPath |
| Verification recorded | TBD | This file |

## Gap Analysis

| Gap | Impact | Follow-up |
| --- | --- | --- |
| TBD | TBD | TBD |
"@

$report = @"
# $Id $Title Report

Created: $date
PDCA Phase: Report
Slice: $Id $Title

## Summary

TBD

## Delivered

- TBD

## Test Evidence

- TBD

## Residual Risks

- TBD
"@

$feedback = @"
# $Id $Title Feedback

Created: $date
PDCA Phase: Act
Slice: $Id $Title

## Feedback Items

| Source | Finding | Decision |
| --- | --- | --- |
| TBD | TBD | TBD |

## PDCA Act Decision

TBD
"@

Write-NewFile $planPath $plan
Write-NewFile $designPath $design
Write-NewFile $analysisPath $analysis
Write-NewFile $reportPath $report
Write-NewFile $feedbackPath $feedback

if (Test-Path $backlogPath) {
  $backlogLine = "| $Id | $Title | $Priority | generated by qa/new-ticket.ps1 |"
  $backlogContent = Get-Content -Path $backlogPath -Raw
  if (-not $backlogContent.Contains("| $Id |")) {
    $sourceClusterMarker = "`r`n## Source Clusters"
    if (-not $backlogContent.Contains($sourceClusterMarker)) {
      $sourceClusterMarker = "`n## Source Clusters"
    }

    if ($backlogContent.Contains($sourceClusterMarker)) {
      $updatedBacklog = $backlogContent.Replace($sourceClusterMarker, "`r`n$backlogLine`r`n## Source Clusters")
      Set-Content -Path $backlogPath -Value $updatedBacklog -Encoding UTF8
    } else {
      Add-Content -Path $backlogPath -Value $backlogLine -Encoding UTF8
    }
  }
}

Write-Output "NEW_TICKET_CREATED $Id $baseName"
